game_parser/api/urls.py
from django.urls import path

from game_parser.api.cz import QuestGiversView, VendorCyclicQuests

urlpatterns = [
    path("quest_vendors/", QuestGiversView.as_view()),
    path("quests/", VendorCyclicQuests.as_view()),
]

game_parser/urls.py
from django.urls import include, path

from game_parser.views import (
    EscapeMap,
    IndexView,
    TasksListView,
    TaskVendorsList,
    VendorQuestsList,
)

app_name = "game_parser"

urlpatterns = [
    path("tasks/", TasksListView.as_view()),
    path("map/", EscapeMap.as_view()),
    path("map/<str:location>", EscapeMap.as_view()),
    path("api/", include("game_parser.api.urls")),
    path("task_vendors/", TaskVendorsList.as_view(), name="task_vendors"),
    path(
        "task_vendors/<int:vendor_id>/quests/",
        VendorQuestsList.as_view(),
        name="vendor_tasks",
    ),
    path("", IndexView.as_view(), name="index"),
]

stalker_op22_cyclic_quest_wiki_proj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

from stalker_op22_cyclic_quest_wiki.sitemap import sitemaps as wiki_sitemap

sitemaps = {
    **wiki_sitemap,
}

urlpatterns = [
    path(
        "",
        include("stalker_op22_cyclic_quest_wiki.urls"),
        name="stalker_op22_cyclic_quest_wiki",
    ),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if "game_parser" in settings.INSTALLED_APPS:
    urlpatterns += [
        path("game_parser/", include("game_parser.urls"), name="game_parser"),
    ]

game_parser/models/anomaly.py
from django.db import models


class Anomaly(models.Model):
    section_name = models.CharField(max_length=255, null=False, unique=True)
    class_name = models.CharField(max_length=255, null=False)
    visual_str = models.CharField(max_length=255, null=True)
    hit_type = models.CharField(max_length=255, null=True)
    article = models.ForeignKey(
        "EncyclopediaArticle",
        null=True,
        on_delete=models.SET_NULL,
    )

    class Meta:
        verbose_name = "Аномалия"
        verbose_name_plural = "Аномалии"

    def __str__(self) -> str:
        return self.section_name

game_parser/models/character.py
from django.db import models


class Character(models.Model):
    game_code = models.CharField(null=False, max_length=255, unique=True)
    name = models.CharField(null=True, max_length=255)

    def __str__(self) -> str:
        return f"NPC {self.game_code} {self.name}"

game_parser/models/custom_inventory_box.py
from django.db import models


class InventoryBox(models.Model):
    """
    Похоже, это тайник в виде рюкзака, из которого можно достать предметы
    """

    section_name = models.CharField(
        max_length=255,
        verbose_name="Название секции",
        unique=True,
    )
    source_file_name = models.CharField(
        max_length=255,
        verbose_name="Путь к файлу(custom_data)",
    )
    items_raw = models.CharField(
        max_length=1000,
        verbose_name="Строка с предметами",
        null=True,
    )
    visual_str = models.CharField(
        max_length=255,
        verbose_name="Внешний вид(название - visual)",
        null=True,
    )

    class Meta:
        verbose_name = "Тайник"
        verbose_name_plural = "Тайники"

    def __str__(self) -> str:
        return f"Тайник {self.section_name}"


class ItemInTreasureBox(models.Model):

    item = models.ForeignKey(
        "BaseItem",
        null=False,
        on_delete=models.CASCADE,
        verbose_name="Предмет",
    )
    box = models.ForeignKey(
        "InventoryBox",
        null=False,
        on_delete=models.CASCADE,
        verbose_name="Тайник",
    )
    count = models.IntegerField(null=True, verbose_name="Количество")

    class Meta:
        verbose_name = "Предметы в тайнике"
        verbose_name_plural = "Предметы в тайниках"
        unique_together = [
            ["item", "box"],
        ]

    def __str__(self) -> str:
        return f"{self.count} {self.item} в {self.box}"

game_parser/models/cycle_task_vendors.py
from typing import TYPE_CHECKING

from django.db import models

if TYPE_CHECKING:
    from game_parser.models import SpawnItem, SpawnReward, StorylineCharacter


class CycleTaskVendor(models.Model):
    game_story_id_raw = models.PositiveSmallIntegerField(
        null=False,
        verbose_name="game id",
        unique=True,
    )
    vendor_id = models.PositiveSmallIntegerField(
        null=False,
        verbose_name="game id",
        unique=True,
    )
    game_story_id = models.ForeignKey(
        null=True,
        to="GameStoryId",
        on_delete=models.SET_NULL,
        unique=True,
    )

    class Meta:
        verbose_name = "ID НПС, выдающий циклические задания"
        verbose_name_plural = "ID Выдающих ЦЗ НПС"

    def __str__(self) -> str:
        return f"{self.game_story_id}, {self.vendor_id}"

    def get_spawn_section(self) -> "SpawnItem | None":
        game_story_id = self.game_story_id
        if not game_story_id:
            return None
        return game_story_id.spawn_section

    def _get_game_story_character_profile(self) -> "StorylineCharacter | None":
        game_story_id = self.game_story_id
        if not game_story_id:
            return None
        return game_story_id.get_stalker_profile()

    def _get_spawn_section_npc_profile(self) -> "StorylineCharacter | None":
        spawn_section = self.get_spawn_section()
        if not spawn_section:
            return None
        return spawn_section.character_profile

    def get_npc_profile(self) -> "StorylineCharacter | None":
        return (
            self._get_spawn_section_npc_profile()
            or self._get_game_story_character_profile()
        )

    def get_spawn_item(self) -> "SpawnItem | None":
        return self.get_spawn_section()

    def _get_spawn_rewards_from_game_story_id(self) -> "list[SpawnReward]":
        game_story_id = self.game_story_id
        if not game_story_id:
            return []
        spawn_section_custom = game_story_id.spawn_section_custom
        if not spawn_section_custom:
            return []
        return list(spawn_section_custom.spawn_rewards.all())

    def _get_npc_spawn_rewards(self) -> "list[SpawnReward]":
        npc_profile = self.get_npc_profile()
        if not npc_profile:
            return []
        result = []
        for custom_spawn_item in npc_profile.customspawnitem_set.all():
            result.extend(list(custom_spawn_item.spawn_rewards.all()))
        return result

    def get_spawn_rewards(self) -> "list[SpawnReward]":
        return (
            self._get_spawn_rewards_from_game_story_id() + self._get_npc_spawn_rewards()
        )

game_parser/models/encyclopedia.py
from django.db import models


class EncyclopediaGroup(models.Model):

    name = models.CharField(max_length=255, verbose_name="Название", unique=True)
    name_translation = models.ForeignKey(
        "Translation",
        null=True,
        on_delete=models.SET_NULL,
        related_name="+",
    )

    class Meta:
        verbose_name = "Группа в энциклопедии"
        verbose_name_plural = "Группы в энциклопедии"

    def __str__(self) -> str:
        if self.name_translation and self.name_translation.rus:
            return self.name_translation.rus
        return self.name


class EncyclopediaArticle(models.Model):
    game_id = models.CharField(max_length=255, verbose_name="Игровой id", unique=True)
    name = models.CharField(max_length=255, verbose_name="Название")
    name_translation = models.ForeignKey(
        "Translation",
        null=True,
        on_delete=models.SET_NULL,
        related_name="+",
    )
    group_name = models.CharField(max_length=255, verbose_name="Группа", null=True)
    group = models.ForeignKey("EncyclopediaGroup", null=True, on_delete=models.SET_NULL)
    ltx_str = models.CharField(
        max_length=255,
        null=True,
        verbose_name="Иконка",
        unique=True,
    )
    icon = models.ForeignKey(
        "Icon",
        null=True,
        on_delete=models.SET_NULL,
        related_name="+",
    )
    text = models.TextField(null=False)
    text_translation = models.ForeignKey(
        "Translation",
        null=True,
        on_delete=models.SET_NULL,
        related_name="+",
    )
    artefact = models.ForeignKey(
        "Artefact",
        null=True,
        on_delete=models.SET_NULL,
        related_name="articles",
    )

    class Meta:
        verbose_name = "Статья в энциклопедии"
        verbose_name_plural = "Статьи в энциклопедии"

    def __str__(self) -> str:
        return f"Статья {self.name} в разделе {self.group}"

game_parser/models/game_story_ids.py
from typing import TYPE_CHECKING

from django.db import models

if TYPE_CHECKING:
    from game_parser.models import StorylineCharacter


class GameStoryId(models.Model):

    story_id = models.PositiveSmallIntegerField(
        null=False,
        verbose_name="id в игре",
        unique=True,
    )
    section_name = models.CharField(
        null=False,
        max_length=255,
        verbose_name="Название секции",
        unique=True,
    )

    item = models.ForeignKey(
        null=True,
        to="BaseItem",
        on_delete=models.SET_NULL,
        blank=True,
        verbose_name="Предмет",
    )
    treasure = models.ForeignKey(
        null=True,
        to="Treasure",
        on_delete=models.SET_NULL,
        blank=True,
        verbose_name="Тайник",
    )
    character = models.ForeignKey(
        null=True,
        to="StorylineCharacter",
        on_delete=models.SET_NULL,
        blank=True,
        verbose_name="Предмет",
    )
    spawn_section = models.ForeignKey(
        null=True,
        to="SpawnItem",
        on_delete=models.SET_NULL,
        blank=True,
        verbose_name="Секция спавна",
    )
    spawn_section_custom = models.ForeignKey(
        null=True,
        to="CustomSpawnItem",
        on_delete=models.SET_NULL,
        blank=True,
        verbose_name="Кастоная секция спавна",
    )

    class Meta:
        verbose_name = "Связь id с секциями"
        verbose_name_plural = "Связи id с секциями"

    def __str__(self) -> str:
        return f"{self.story_id}"

    def get_stalker_profile(self) -> "StorylineCharacter | None":
        character = None
        if self.spawn_section:
            character = character or self.spawn_section.character_profile
        if self.spawn_section_custom:
            character = character or self.spawn_section_custom.character_profile
        return character or self.character

game_parser/models/game_vertex.py
from typing import TYPE_CHECKING

from django.db import models

if TYPE_CHECKING:
    from game_parser.models import SpawnReward


class GameVertex(models.Model):
    vertex_id = models.PositiveIntegerField(null=False, unique=True)

    level_point_x = models.FloatField(null=False)
    level_point_y = models.FloatField(null=False)
    level_point_z = models.FloatField(null=False)

    game_point_x = models.FloatField(null=False)
    game_point_y = models.FloatField(null=False)
    game_point_z = models.FloatField(null=False)

    level_id_raw = models.PositiveIntegerField(null=False)
    location = models.ForeignKey("Location", null=True, on_delete=models.SET_NULL)
    level_vertex_id = models.PositiveIntegerField(null=False)
    vertex_type_raw = models.CharField(null=False, max_length=512)
    level_points_raw = models.CharField(null=False, max_length=512)
    edges_raw = models.CharField(null=False, max_length=512)

    class Meta:
        verbose_name = "Узел графа игры"

    spawn_rewards: "models.Manager[SpawnReward]"

    def __str__(self) -> str:
        return f"Вершина {self.vertex_id} на локации {self.level_id_raw}"

game_parser/models/translation.py
from django.db import models


class Translation(models.Model):

    code = models.CharField(
        max_length=128,
        null=False,
        verbose_name="Код названия",
        unique=True,
    )
    rus = models.TextField(verbose_name="Русский", null=False)
    eng = models.TextField(verbose_name="Английский", null=False)
    ukr = models.TextField(verbose_name="Украинский", null=False)
    pln = models.TextField(verbose_name="Польский", null=False)
    fra = models.TextField(verbose_name="Французский", null=False)

    class Meta:
        verbose_name = "Перевод"
        verbose_name_plural = "Переводы"

    def __str__(self) -> str:
        return f"{self.code} {self.rus}"

game_parser/views.py
import re
from typing import Any

from django.db.models.functions import Lower
from django.http.response import Http404
from django.urls import reverse
from django.views.generic import TemplateView

from game_parser.logic.tasks_grouping import collect_info, collect_vendor_tasks
from game_parser.models import (
    CycleTaskVendor,
    Location,
    LocationMapInfo,
    SpawnItem,
    StorylineCharacter,
)
from game_parser.models.quest import CyclicQuest, QuestKinds


class TasksListView(TemplateView):

    template_name = "vendors_tasks_list.html"

    def get_context_data(self, **kwargs: Any) -> dict:
        data = collect_info()
        return {"vendors_quests": data}


class EscapeMap(TemplateView):
    template_name = "escape_map.html"
    location_name = "L01_escape"

    def get_context_data(self, **kwargs: Any) -> dict:
        location_name = kwargs.get("location", self.location_name)
        location = Location.objects.annotate(name_lowe=Lower("name")).get(
            name_lowe=location_name.lower(),
        )
        spawn_items = SpawnItem.objects.filter(location=location)
        location_info = LocationMapInfo.objects.get(location=location)
        offset_re = re.compile(
            r"\s*(?P<min_x>.*),\s*(?P<min_y>.*),\s*(?P<max_x>.*),\s*(?P<max_y>.*)",
        )
        if location_info.bound_rect_raw is None:
            raise ValueError
        rm = offset_re.match(location_info.bound_rect_raw)
        if rm is None:
            msg = "не распарсились границы локи"
            raise ValueError(msg)
        (min_x, min_y, max_x, max_y) = (
            float(rm.group("min_x")),
            float(rm.group("min_y")),
            float(rm.group("max_x")),
            float(rm.group("max_y")),
        )

        y_level_offset = -(max_y + min_y)
        return {
            "layer_image_url": location_info.map_image.url,
            "map_size": (location_info.map_image.width, location_info.map_image.height),
            "map_offset": (min_x, min_y, max_x, max_y),
            "items": [self._spawn_item_to_dict(item) for item in spawn_items],
            "y_level_offset": y_level_offset,
        }

    def _spawn_item_to_dict(self, spawn_item: SpawnItem) -> dict | None:
        position_re = re.compile(r"\s*(?P<x>.*),\s*(?P<y>.*),\s*(?P<z>.*)")
        rm = position_re.match(spawn_item.position_raw)
        if not rm:
            return None
        (x, _, z) = float(rm.group("x")), float(rm.group("y")), float(rm.group("z"))
        position = (x, z)
        name = spawn_item.name
        section_name = spawn_item.section_name

        return {
            "position": position,
            "name": name,
            "section_name": section_name,
        }


class TaskVendorsList(TemplateView):
    template_name = "task_vendors_list/task_vendor_list.html"

    def get_context_data(self, **kwargs: Any) -> dict:
        vendors = CycleTaskVendor.objects.all()
        return {
            "vendors": [self._vendor_to_dict(vendor) for vendor in vendors],
        }

    def _vendor_to_dict(self, vendor: CycleTaskVendor) -> dict:
        npc_profile = vendor.get_npc_profile()
        return {
            "image_path": (
                self._get_npc_profile_icon(npc_profile) if npc_profile else None
            ),
            "name": (
                npc_profile.name_translation.rus
                if npc_profile and npc_profile.name_translation
                else None
            ),
            "tasks_count": vendor.cyclicquest_set.count(),
            "has_chain": vendor.cyclicquest_set.filter(type=QuestKinds.CHAIN).exists(),
            "quests_link": reverse(
                "game_parser:vendor_tasks",
                kwargs={"vendor_id": vendor.id},
            ),
        }

    def _get_npc_profile_icon(self, npc_profile: StorylineCharacter) -> str | None:
        if npc_profile.icon and npc_profile.icon.icon and npc_profile.icon.icon.url:
            return npc_profile.icon.icon.url
        return None


class VendorQuestsList(TemplateView):
    template_name = "vendor_quests_list/tasks_list.html"

    # pylint: disable=arguments-differ
    def get_context_data(self, vendor_id: int) -> dict[str, Any]:  # type: ignore[override] # зависит от конфига url-ов. Думаю так лучше
        try:
            vendor = CycleTaskVendor.objects.get(id=vendor_id)
        except Exception as ex:
            msg = "Incorrect vendor ID"
            raise Http404(msg) from ex
        vendor_tasks = CyclicQuest.objects.filter(vendor=vendor)
        vendor_profile = vendor.get_npc_profile()
        if vendor_profile is None:
            raise ValueError
        return {
            "vendor_task_info": collect_vendor_tasks(vendor_tasks, vendor_profile),
            "vendor": vendor_profile,
        }


class IndexView(TemplateView):
    template_name = "parser_index.html"

    def get_context_data(self, **kwargs: Any) -> dict:
        return {}

game_parser/templates/ammo_reward.html
<div>
    <div class="d-flex flex-row">
        <div class="d-flex flex-column justify-content-center">
            <div>
                {{ reward.items_count }} пачек
            </div>
            <div>
                ({{ reward.ammo_count }} патронов)
            </div>
        </div>
        <div class="d-flex flex-column">
            {% if reward.item.icon %}
                <img src="{{ reward.item.icon.url }}"
                     width="{{ reward.item.icon.width }}"
                     height="{{ reward.item.icon.height }}"
                     alt="{{ reward.item.item_label }}">
            {% endif %}
            <div class="d-flex flex-row">
                <div>
                    {{ reward.item.item_label }}("{{ reward.item.item_id }}")
                </div>
            </div>
        </div>
    </div>
</div>

game_parser/templates/ammo_target.html
<div>
    <div class="d-flex flex-row">
        <div class="d-flex flex-column justify-content-center">
            <div>
                {{ target.items_count }} пачек
            </div>
            <div>
                ({{ target.ammo_count }} патронов)
            </div>
        </div>
        <div class="d-flex flex-column">
            {% if target.item.icon %}
                <img src="{{ target.item.icon.url }}"
                     width="{{ target.item.icon.width }}"
                     height="{{ target.item.icon.height }}"
                     alt="{{ target.item.item_label }}">
            {% endif %}
            <div class="d-flex flex-row">
                <div>
                    {{ target.item.item_label }}("{{ target.item.item_id }}")
                </div>
            </div>
        </div>
    </div>
</div>

game_parser/templates/escape_map.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <title>Escape Map</title>
        {% if meta_description %}
            <meta name="description"
                  content="{{ meta_description }}" />
        {% endif %}
        {% if meta_keywords %}
            <meta name="keywords"
                  content="{{ meta_keywords }}" />
        {% endif %}
        <style>
            #map {
                width: 90vw;
                height: 90vh;
            }
        </style>
        <link rel="stylesheet"
              href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
              crossorigin="" />
        <!-- Make sure you put this AFTER Leaflet's CSS -->
        <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
                crossorigin=""></script>
        {{ items|json_script:"items" }}
        {{ map_offset|json_script:"map_offset" }}
        {{ y_level_offset|json_script:"y_level_offset" }}
        <script>
            const imagePath = "{{ layer_image_url }}";
            const items = JSON.parse(document.getElementById('items').textContent);
            const map_offset = JSON.parse(document.getElementById('map_offset').textContent);
            const yLevelOffset = JSON.parse(document.getElementById('y_level_offset').textContent);
            const min_x = map_offset[0];
            const min_y = map_offset[1];
            const max_x = map_offset[2];
            const max_y = map_offset[3];


            document.addEventListener("DOMContentLoaded", () => {

                // Using leaflet.js to pan and zoom a big image.
                // See also: http://kempe.net/blog/2014/06/14/leaflet-pan-zoom-image.html
                // create the slippy map
                const map = L.map('map', {
                    minZoom: -1,
                    maxZoom: 6,
                    center: [0, 0],
                    zoom: 1,
                    crs: L.CRS.Simple
                });
                // calculate the edges of the image, in coordinate space
                const southWest = map.unproject([min_x, min_y], 0);
                const northEast = map.unproject([max_x, max_y], 0);
                const bounds = new L.LatLngBounds(southWest, northEast);
                // add the image overlay,
                // so that it covers the entire map
                L.imageOverlay(imagePath, bounds).addTo(map);
                // tell leaflet that the map is exactly as big as the image
                map.setMaxBounds(bounds);
                items.forEach(
                    (item) => {
                        const marker = new L.Marker([item.position[1] + yLevelOffset, item.position[0]])
                        marker.bindPopup(`${item.position}, ${item.name}, ${item.section_name}`)
                        marker.addTo(map);
                    }
                );

                const Coordinates = L.Control.extend({
                    onAdd: map => {
                        const container = L.DomUtil.create("div");
                        map.addEventListener("mousemove", e => {
                            container.innerHTML = `
          <h2>Latitude is
            ${e.latlng.lat.toFixed(4)} <br>
            and Longitude is  ${e.latlng.lng.toFixed(4)}
            </h2>
          `;
                        });
                        return container;
                    }
                });
                map.addControl(new Coordinates({
                    position: "bottomleft"
                }));

            });
        </script>
    </head>
    <body>
        <div class="main">
            <div class="wrapper">
                <h3 class="mb-3">
                    Bounds: {{ map_offset }}
                </h3>
                <div id="map">
                </div>
            </div>
        </div>
    </body>
</html>

game_parser/templates/game_parser_base.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, initial-scale=1.0">
        {% if meta_description %}
            <meta name="description"
                  content="{{ meta_description }}" />
        {% endif %}
        {% if meta_keywords %}
            <meta name="keywords"
                  content="{{ meta_keywords }}" />
        {% endif %}
        <title>
            {% block title %}
                Энциклопедия по ОП-2.2
            {% endblock title %}
        </title>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
                crossorigin="anonymous"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
              crossorigin="anonymous">
        <link rel="stylesheet"
              href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
              crossorigin="" />
        <!-- Make sure you put this AFTER Leaflet's CSS -->
        <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
                crossorigin=""></script>
        {% block extrahead %}
        {% endblock extrahead %}
    </head>
    <body>
        <header>
            <nav>
                <div class="d-flex flex-row ">
                    <div class="mx-3">
                        <a href="{% url "game_parser:index" %}">Главная</a>
                    </div>
                    <div class="mx-3">
                        <a href="{% url "game_parser:task_vendors" %}">Циклические задания</a>
                    </div>
                    <div class="mx-3">
                        <a
                            {#                        href="#"#}
                        >Поиск предметов. В разработке</a>
                    </div>
                    <div class="mx-3">
                        <a
                            {#                        href="#"#}
                        >Торговля. В разработке</a>
                    </div>
                </div>
            </nav>
        </header>
        <main>
            {% block main %}
            {% endblock main %}
        </main>
        {#<footer>#}
        {#    <p>&copy; 2021 Название вашей компании. Все права защищены.</p>#}
        {#</footer>#}
    </body>
</html>

game_parser/templates/item_reward.html
<div>
    <div class="d-flex flex-row">
        <div class="d-flex flex-column justify-content-center">
            <div>
                {{ reward.items_count }} x
            </div>
        </div>
        <div class="d-flex flex-column">
            {% if reward.item.icon %}
                <img src="{{ reward.item.icon.url }}"
                     width="{{ reward.item.icon.width }}"
                     height="{{ reward.item.icon.height }}"
                     alt="{{ reward.item.item_label }}">
            {% endif %}
            <div class="d-flex flex-row">
                <div>
                    {{ reward.item.item_label }}("{{ reward.item.item_id }}")
                </div>
            </div>
        </div>
    </div>
</div>

game_parser/templates/item_target.html
<div>
    <div class="d-flex flex-row">
        <div class="d-flex flex-column justify-content-center">
            <div>
                {{ target.items_count }} x
            </div>
        </div>
        <div class="d-flex flex-column">
            <img src="{{ target.item.icon.url }}"
                 width="{{ target.item.icon.width }}"
                 height="{{ target.item.icon.height }}"
                 alt="{{ target.item.item_label }}">
            <div class="d-flex flex-row">
                <div>
                    {{ target.item.item_label }}("{{ target.item.item_id }}")
                </div>
            </div>
        </div>
    </div>
</div>

game_parser/templates/item_with_state_target.html
<div>
    <div class="d-flex flex-row">
        <div class="d-flex flex-column justify-content-center">
            <div>
                {{ target.items_count }} x
            </div>
        </div>
        <div class="d-flex flex-column">
            {% if target.item.icon %}
                <img src="{{ target.item.icon.url }}"
                     width="{{ target.item.icon.width }}"
                     height="{{ target.item.icon.height }}"
                     alt="{{ target.item.item_label }}">
            {% endif %}
            <div class="progress min-width-500px">
                <div class="progress-bar  bg-error"
                     role="progressbar"
                     style="width: {{ before_width }}%"
                     aria-valuenow="{{ target.state.min }}"
                     aria-valuemin="0"
                     aria-valuemax="100">
                </div>
                <div class="progress-bar bg-success progress-bar-striped progress-bar-animated d-flex flex-row justify-content-between small"
                     role="progressbar"
                     style="width: {{ target_width }}%"
                     aria-valuenow="{{ target.state.max }}"
                     aria-valuemin="0"
                     aria-valuemax="100">
                    {% if after_width > 0 %}
                        <span>{{ target.state.min }}%</span>
                        <span>{{ target.state.max }}%</span>
                    {% else %}
                        <span>{{ target.state.min }}% +</span>
                    {% endif %}
                </div>
                <div class="progress-bar  bg-error"
                     role="progressbar"
                     style="width: {{ after_width }}%"
                     aria-valuenow="100"
                     aria-valuemin="0"
                     aria-valuemax="100">
                </div>
            </div>
            <div class="d-flex flex-row">
                <div>
                    {% if target_cond_str %}
                        {{ target_cond_str }}
                    {% endif %}
                    {{ target.item.item_label }}("{{ target.item.item_id }}")
                </div>
            </div>
        </div>
    </div>
</div>

game_parser/templates/lager_target.html
{% load parser_map %}
<div>
    {{ target.game_id }}
    {% if target.map_info %}
        {% render_map_item target.map_info target.game_id %}
    {% endif %}
</div>

game_parser/templates/money_reward.html
<div>
    Деньги {{ reward.count }} RUB
</div>

game_parser/templates/stalker_target.html
{% load parser_map %}
<div>
    <h6>
        {{ target.stalker_str }}
    </h6>
    <div>
        Возможные места спавна
    </div>
    <div>
        {% for point in target.possible_points %}
            <div class="my-3">
                {% render_map_item point target.game_id forloop.counter %}
            </div>
        {% endfor %}
    </div>
</div>

game_parser/templates/task.html
{% load parser_tasks %}
<div class="task d-flex flex-row justify-content-between border-bottom border-3 mb-2">
    <div class="target flex-column">
        <h5 class="align-self-center">
            Цель
        </h5>
        {% render_target task.target %}
    </div>
    <div class="test-text mx-3">
        {{ task.text }}
    </div>
    <div class="rewards d-flex flex-column">
        <h5 class="align-self-center">
            Награда
        </h5>
        {% for reward in task.rewards %}
            {% render_reward reward %}
        {% endfor %}
    </div>
</div>

game_parser/templates/treasure_reward.html
<div>
    <div>
        Тайник
    </div>
    <div>
        <img src="{{ reward.icon.url }}"
             width="{{ reward.icon.width }}"
             height="{{ reward.icon.height }}"
             alt="{{ reward.reward_name }}">
    </div>
</div>